# Generated by Django 6.0.5 on 2026-05-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Unknown', max_length=500)),
                ('last_name', models.CharField(default='Unknown', max_length=500)),
                ('phone', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='noemail@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='user', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('budget', models.IntegerField(default=0)),
                ('property_type', models.CharField(default='single-room', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Unverified', max_length=500)),
                ('liked', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('room_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('beds', models.IntegerField(blank=True, default=1, null=True)),
                ('bath', models.IntegerField(default=1)),
                ('sqft', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
