# Generated by Django 6.0.5 on 2026-07-06 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookroom_notification_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='preferred_time',
            field=models.CharField(default='12:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='bookroom',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='move_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='preferred_date',
            field=models.DateField(),
        ),
    ]
