# Generated by Django 6.0.5 on 2026-07-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookroom_preferred_time_bookroom_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='liked',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_rooms', to='app.user'),
        ),
    ]
