# Generated by Django 6.0.5 on 2026-07-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_room_liked_bookroom_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookroom',
            old_name='is_verified',
            new_name='is_verified_by_admin',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='is_verified_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
